version: '3.6'

services:
  jekyll:
    image: jekyll/jekyll:4
    #command: bundle update
    command: jekyll serve --watch --incremental --open-url --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
