version: '3.6'

services:
  jekyll:
    image: jekyll/jekyll:latest

    command: gem install kramdown ~ 2.0.0
    command: bundler
    command: jekyll serve --watch --incremental --open-url --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
