- name: HTMLProofer
  # You may pin to the exact commit or the version.
  # uses: chabad360/htmlproofer@2a7ae5816b7173dbbc37cf4cfc33ca6c47c96ecc
  uses: chabad360/htmlproofer@v1.1
  with:
    # The directory to scan
    directory: ".\_sites"
    # HTMLProofer options
    arguments: # optional
